global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets:
          - fastapi:8080

  - job_name: "airflow"
    metrics_path: /admin/metrics
    static_configs:
      - targets:
          - airflow-webserver:8080
